"""empty message

Revision ID: 4390045bcf5
Revises: None
Create Date: 2015-05-19 20:34:51.830438

"""

# revision identifiers, used by Alembic.
revision = '4390045bcf5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
