"""empty message

Revision ID: 457380eef1f
Revises: 4390045bcf5
Create Date: 2015-05-19 20:37:39.299573

"""

# revision identifiers, used by Alembic.
revision = '457380eef1f'
down_revision = '4390045bcf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pwel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp')
    ### end Alembic commands ###
