"""empty message

Revision ID: 498ed61c5d9
Revises: 4843a790e91
Create Date: 2015-05-19 22:16:52.351349

"""

# revision identifiers, used by Alembic.
revision = '498ed61c5d9'
down_revision = '4843a790e91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holdings', sa.PickleType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Trade', sa.String(length=64), nullable=True),
    sa.Column('Symbol', sa.String(length=64), nullable=True),
    sa.Column('Shares', sa.Float(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.Column('Comission', sa.Float(), nullable=True),
    sa.Column('Fee', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('portfolios')
    ### end Alembic commands ###
